### ISSUE TITLE
Correct Credentials, appears to be missing a node module

### ISSUE THREAD

**Issue by ColinTravis** [thobach/MMM-MicrosoftToDo#93]
Hi there, recently configured this, all the correct credentials are in place, but upon rebooting the Magic Mirror container, it throws an error showing that evidently, there is a module missing:

```
[20.01.2023 16:55.17.281] [ERROR] Error: Cannot find module 'logger'
Require stack:
- /opt/magic_mirror/modules/MMM-MicrosoftToDo/node_helper.js
- /opt/magic_mirror/js/app.js
- /opt/magic_mirror/serveronly/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._resolveFilename (/opt/magic_mirror/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/magic_mirror/modules/MMM-MicrosoftToDo/node_helper.js:10:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/magic_mirror/modules/MMM-MicrosoftToDo/node_helper.js',
    '/opt/magic_mirror/js/app.js',
    '/opt/magic_mirror/serveronly/index.js'
  ]

```

**Comment by thobach** [comment]
Hi @ColinTravis, The error is related to a missing node.js module named "logger". According to https://docs.magicmirror.builders/development/logger.html it should be installed together with main Magic Mirror application. Could you please confirm that in the magic mirror subfolder "js" there is a file named "logger.js" that looks like this: https://github.com/MichMich/MagicMirror/blob/master/js/logger.js? And that the magic mirror's package.json file contains an entry like this: https://github.com/MichMich/MagicMirror/blob/master/package.json#L93?

**Comment by thobach** [comment]
Thanks for confirming, though I doubt it was due to an older version as that file and logging mechanism exists for many years.
